services:

#  mysql:
#    image: mysql:8.0.43
#    restart: always
#    container_name: mysql
#    environment:
#      MYSQL_DATABASE: sales
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#      MYSQL_ROOT_PASSWORD: rootpassword
#    volumes:
#      - ./data/mysql_database:/var/lib/mysql
#      - ./data/mysql_rootfolder:/root/data
#    ports:
#      - "3306:3306"
#    networks:
#      capstone-net:
#        ipv4_address: 172.30.0.10

#  phpmyadmin:
#    image: phpmyadmin:5.0
#    container_name: phpmyadmin
#    restart: always
#    ports:
#      - "8080:80"
#    environment:
#      - PMA_ARBITRARY=1
#      - PMA_HOST=172.30.0.10
#      - PMA_PORT=3306
#      - PMA_USER=root
#      - PMA_PASSWORD=rootpassword
#    networks:
#      capstone-net:
#        ipv4_address: 172.30.0.11

#  mongo:
#    image: mongo:5.0
#    restart: unless-stopped
#    container_name: mongo
#    environment:
#      MONGO_INITDB_DATABASE: catalog
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
#    volumes:
#      - ./data/mongo_database:/data/db:rw
#      - ./02-Query-data-in-NoSQL-Databases/mongo_start_scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
#      - ./data/mongo_rootfolder:/root/data:rw
#    ports:
#      - "27017:27017"
#    networks:
#      capstone-net:
#        ipv4_address: 172.30.0.12


networks:
  capstone-net:
    external: true
    name: capstone-net